# Generated by Django 5.0.3 on 2024-04-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_heading',
            field=models.CharField(blank=True, help_text='Mission statement title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_statement',
            field=models.CharField(blank=True, help_text='Mission statement description', max_length=255),
        ),
    ]
