# Generated by Django 5.0.3 on 2024-04-04 20:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(),
        ),
    ]
