# Generated by Django 5.0.3 on 2024-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_mission_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='mission_statement',
            field=models.TextField(),
        ),
    ]
