# Generated by Django 5.0.3 on 2024-04-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_mission_statement'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='card_button_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to from the card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_button_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
