# Generated by Django 5.0.3 on 2024-04-05 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_card_button_link_homepage_card_button_text_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_image',
            field=models.ForeignKey(blank=True, help_text='First image in Carousel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_image_desc',
            field=models.CharField(blank=True, help_text='First image description', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_image',
            field=models.ForeignKey(blank=True, help_text='Second image in Carousel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_image_desc',
            field=models.CharField(blank=True, help_text='First image description', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_image',
            field=models.ForeignKey(blank=True, help_text='Third image in Carousel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_image_desc',
            field=models.CharField(blank=True, help_text='First image description', max_length=255),
        ),
    ]
