# Generated by Django 5.0.3 on 2024-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_first_image_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='first_image_description',
            new_name='first_slide_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='first_image',
            new_name='first_slide_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='second_image_description',
            new_name='first_slide_label',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='third_image_description',
            new_name='second_slide_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='second_image',
            new_name='second_slide_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='third_image',
            new_name='third_slide_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_slide_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
